### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by asaaki** [jgm/cmark#1]
Can you add a license, please?

**Comment by jgm** [comment]
There's already a license:  see COPYING.

**Comment by asaaki** [comment]
Ah, okay, my fault. Was expecting a LICENSE file like in the CommonMark repo.

**Comment by jgm** [comment]
Yes, it's a bit confusing.  I could change it back, but I seem to
recall having some reason for using COPYING.

**Comment by asaaki** [comment]
Nevermind, everthing is fine.
