### ISSUE TITLE
Syntax highlighting support in <code>

### ISSUE THREAD

**Issue by pickfire** [jgm/cmark#110]
Hi, I would like to know if there is any way I can add syntax hightlighting in `<code>` block.

**Comment by jgm** [comment]
You might check out jgm/lcmark.  It has a sample filter for
doing highlighting (in the examples directory).

+++ Ivan Tham [Mar 17 16 10:47 ]:

**Comment by pickfire** [comment]
Ah, looks nice, I didn't know about that. But it might be slower than cmark as it is not written in C.

Thanks a lot.

**Comment by jgm** [comment]
+++ Ivan Tham [Mar 17 16 22:35 ]:
>   Ah, looks nice, I didn't know about that. But it might be slower than
>   cmark as it is not written in C.

lcmark is a wrapper over libcmark, so it's really pretty
fast, nearly as fast as cmark!  The only slow part is the
highlighting which shells out to a python program.

**Comment by pickfire** [comment]
Oh, now I really hope that there is a highlight program in C.
