### ISSUE TITLE
Release 0.25.0 has version number 0.25.1

### ISSUE THREAD

**Issue by nwellnhof** [jgm/cmark#112]
PROJECT_VERSION_PATCH in CMakeLists.txt wasn't reset to 0.

**Comment by jgm** [comment]
Blast !  How do I fix this though?  A new release with the same code and new version number?

**Comment by nwellnhof** [comment]
Right now, it's mostly a cosmetic problem. I can see two solutions

- Release 0.25.1 with no changes to 0.25.0.
- Do nothing and make sure to never make a 0.25.1 release.

**Comment by jgm** [comment]
Released 0.25.1.
