### ISSUE TITLE
EOL character weirdness 

### ISSUE THREAD

**Issue by crystalfp** [jgm/cmark#113]
I have a .md file with CRLF end of line, except one line that ends with a CR only. This line is followed by an empty line, that is CRLF only, to signal the paragraph end.
The file is [here](https://dl.dropboxusercontent.com/u/2571325/eol.md)

The CR is interpreted as softbreak, that's OK (see also another lone CR at line 9) , but the parser don't see the following end of paragraph and joins the two paragraphs together.

Currently I call the parser with the following options: CMARK_OPT_NORMALIZE | CMARK_OPT_VALIDATE_UTF8 | CMARK_OPT_SMART
Seems this happens even if I add CMARK_OPT_HARDBREAKS or remove CMARK_OPT_NORMALIZE.

The spec says (pag. 4) that a CR alone is a valid line end, so I don't understand where the following CRLF is gone.

The fix is trivial, simply edit the file changing the guilty EOL, but who knows where in the heap of files lurks another lone CR?

This happens with the latest cmark 0.25.1 on Windows 7 64bits.

**Comment by jgm** [comment]
Closed by 03a6547b8cea55c8917214a363cadda5b7cffd31
