### ISSUE TITLE
Cmark skipping first character in line

### ISSUE THREAD

**Issue by crystalfp** [jgm/cmark#114]
When this [commonmark file](https://dl.dropboxusercontent.com/u/2571325/bug2.md) is parsed and output, the "Repeatedly" word on line 5 has the "R" missing.

```
By taking it apart

- alternative solutions
	
Repeatedly solving
	
- how techniques
```

IMPORTANT! the two blank lines surrounding the "Repeatedly" line contains a TAB each.

If I delete the tab above the line (line 4) everything works as expected.

To reproduce run `cmark.exe bug2.md`

Windows 7 64 bits, cmark version 0.25.1

Thanks for looking!
mario

**Comment by jgm** [comment]
Closed by b299be03398677fa2a396b649531183485da62e7
