### ISSUE TITLE
Handle CR+LF split across buffer boundaries

### ISSUE THREAD

**Issue by nwellnhof** [jgm/cmark#117]
The following code will process two lines instead of one:

    cmark_parser_feed(parser, "line1\r", 6);
    cmark_parser_feed(parser, "\n", 1);

The parser must keep track whether the last buffer ended with a CR, and skip a LF at the beginning of the next buffer if necessary.

**Comment by jgm** [comment]
Think I've fixed this, but you may want to check what I've done.

**Comment by nwellnhof** [comment]
Your fix is exactly what I had in mind.
