### ISSUE TITLE
cmark_parser_new declaration versus use

### ISSUE THREAD

**Issue by nanis** [jgm/cmark#12]
I decided to try to build this library using Visual Studio 2013 CE for the first time. I do not know much about the internal design decisions ... I just thought it would be a good idea to try it out.

My build failed with:

<pre>[ 32%] Building C object src/CMakeFiles/cmark.dir/main.c.obj
main.c
C:\...\main.c(119) : error C2660: 'cmark_parser_new' : function does not take 1 arguments</pre>

Lo and behold, [cmark.h](https://github.com/jgm/cmark/blob/master/src/cmark.h#L433) has:

    CMARK_EXPORT
    cmark_parser *cmark_parser_new();

Knowing enough C, it is not shocking that some compilers may forgive this, but I am not sure which compiler let [blocks.c](https://github.com/jgm/cmark/blob/1533c8fbad3acc48e6a2f0a1e305aeb5932b3bbd/src/blocks.c#L53) compile.

<pre>C:\...> cl /?
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x64</pre>

**Comment by jgm** [comment]
Thanks!  It is indeed surprising that gcc and clang both let this go
without comment!  I'm obviously trusting the compiler way too much.

+++ A. Sinan Unur [Mar 09 15 21:13 ]:

**Comment by nanis** [comment]
Actually, I think it is `cl` that is wrong here (but, I think, in a good way ;-) at least according to my reading of this [C FAQ entry](http://c-faq.com/decl/implfdecl.html):

> Functions which are called without a declaration in scope, perhaps because the first call precedes the function's definition, are assumed to be declared as if by:

>	    extern int f();

> That is, an undeclared function is assumed to return int, and to ***accept an unspecified number of arguments***

It looks like I have forgotten that `int f()` and `int f(void)` are not the same. I don't know what the current standard says about this.

Anyway, thank you.

**Comment by nanis** [comment]
So, I was able to locate a copy of the C99 standard. On page 119, it says:

> 14 An identifier list declares only the identifiers of the parameters of the function. An empty
list in a function declarator that is part of a definition of that function specifies that the
function has no parameters. ***The empty list in a function declarator that is not part of a
definition of that function specifies that no information about the number or types of the
parameters is supplied.***<sup>124</sup> (emphasis mine). 

So, while I think we both agree that the declaration of the function should match its definition, if I am reading this correctly, my reaction was wrong.

At least, footnote 124 leads to "6.11.6 Function declarators: The use of function declarators with empty parentheses (not prototype-format parameter type declarators) is an obsolescent feature."

*Thanks!*

**Comment by jgm** [comment]
Thanks for clearing that up.  I'm still glad you caught this, for portability and documentation purposes.

+++ A. Sinan Unur [Mar 09 15 22:36 ]:

**Comment by nwellnhof** [comment]
As @nanis explained, this is normal C behavior. MSVC throws an error because we compile as C++ under this compiler.
