### ISSUE TITLE
Change target in links generated by cmark_markdown_to_html()

### ISSUE THREAD

**Issue by crystalfp** [jgm/cmark#122]
Small enhancement proposal.

In my application I found extremely convenient to use `cmark_markdown_to_html()` to display markdown text in the browser.

However links are rendered as plain `<a href="...">` and thus they open in the same page, destroying the application GUI. My simple solution is to add, after the routine call, a loop that substitutes every `'<a '` string with `'<a target="_blank" '`

Instead I suggest to add another option (call it `CMARK_OPT_TARGET_BLANK`) and change line 278 of html.c from:
```
      cmark_strbuf_puts(html, "<a href=\"");
```
to
```
      if (options & CMARK_OPT_TARGET_BLANK)
          cmark_strbuf_puts(html, "<a target=\"_blank\" href=\"");
      else
         cmark_strbuf_puts(html, "<a href=\"");
```

Thanks for considering!

**Comment by MathieuDuponchelle** [comment]
That's a very specialized use case, wouldn't it be adequately solved by using <http://www.w3schools.com/tags/att_base_target.asp> ?

**Comment by crystalfp** [comment]
Yes! I forgot <base>. 
Thanks for the suggestion. 
Close the feature request. 
Thanks again. 
Mario

Il 03 Maggio 2016 14:08:45 CEST, Mathieu Duponchelle <notifications@github.com> ha scritto:
>That's a very specialized use case, wouldn't it be adequately solved by
>using <http://www.w3schools.com/tags/att_base_target.asp> ?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/cmark/issues/122#issuecomment-216508647

-- 
Inviato da Galaxy Notes con K-9 Mail. Perdonate la brevità.

**Comment by MathieuDuponchelle** [comment]
Can't close, @jgm ^ 

Glad I helped :)
