### ISSUE TITLE
Docs and headers for rendering functions dont mention buffer ownership

### ISSUE THREAD

**Issue by mikeando** [jgm/cmark#124]
It's not clear from the docs what the lifetime of the buffer for the result of calls to `cmark_render_html`
and related calls are.

I see a few options - and there's probably other possibilities too..

1. The buffer is owned by the node that render is called on, and is free'd when that node is destroyed.
2. The buffer is owned by the caller, and the caller is expected to free it.

The second would make more sense to me - but its certainly not clear from the docs or headers. 

The code should simply say something like : "It is the callers responsibility to destroy the returned buffer using `free`".

**Comment by jgm** [comment]
+++ Mike Anderson [Apr 26 16 19:06 ]:
>   It's not clear from the docs what the lifetime of the buffer for the
>   result of calls to cmark_render_html
>   and related calls are.
>
>   I see a few options - and there's probably other possibilities too..
>    1. The buffer is owned by the node that render is called on, and is
>       free'd when that node is destroyed.
>    2. The buffer is owned by the caller, and the caller is expected to
>       free it.

It's 2.  I actually hadn't imagined that anyone would think 1,
so it's not explicit in the documentation.

>   The code should simply say something like : "It is the callers
>   responsibility to destroy the returned buffer using free".

OK. That sounds reasonable.

**Comment by mikeando** [comment]
I guess I've seen too many bad APIs where people write stuff into global buffers (ugh).

I  assume
 
~~~
CMARK_EXPORT const char *cmark_node_get_literal(cmark_node *node);
~~~

(and similar calls) return a buffer owned by the node, and so there's no need to free them explicitly and they'll be freed (and thus become invalid) when the node is destroyed. I.e. the render calls seem to be an exception to the convention used in the rest of the code.

**Comment by jgm** [comment]
+++ Mike Anderson [Apr 26 16 21:51 ]:
>   I guess I've seen too many bad APIs where people write stuff into
>   global buffers (ugh).
>
>   I assume
>CMARK_EXPORT const char *cmark_node_get_literal(cmark_node *node);
>
>   (and similar calls) return a buffer owned by the node, and so there's
>   no need to free them explicitly and they'll be freed (and thus become
>   invalid) when the node is destroyed. I.e. the render calls seem to be
>   an exception to the convention used in the rest of the code.

Actually, no, this function also allocates a buffer that
must be freed by the caller.

Maybe we should have a global note, that all functions that
return char buffers assume that the caller will free them
when finished, instead of putting this note on every
function?

**Comment by mikeando** [comment]
Yep, that'd do. The one case I thought of that it might not be true for is  `cmark_node_get_type_string` - since all the type strings are known at compile time.  It may be worth checking that one isn't doing anything differently.

Do the corresponding `set` style functions take ownership of buffers passed in? I'd assume not, but it seems some of my assumptions have been wrong so far...

Thanks.

Mike A.

**Comment by mikeando** [comment]
OK. So I've dug into the code a little, and it looks to me like its not doing quite what @jgm thinks.
(Unless I'm missing something - which is quite possible)

The code to set a litteral is `cmark_node_set_literal`, which forwards to `cmark_chunk_set_cstr(&node->as.literal, content)`. 

`cmark_chunk_set_cstr` will create a copy of the data and set the `c->alloc=1`.

Conversely `cmark_node_get_lteral` forwards to `cmark_chunk_to_cstr` which has this:

~~~
if(c->alloc) {
   return (char*)c->data;
}
~~~

which means it is returning the original data, not a copy of it. 

The non alloc case actually updates the internal chunk to own the data, and then returns
it.

This means a user should not free the buffers returned by `cmark_node_get_literal`.

**Comment by jgm** [comment]
I glanced at the code too (in responding before) and saw
the memcpy, but missed the subtlety about the alloc flag.

@nwellnhof - is this really how we want it to be working?

In any case, however it does work, this needs to be more
explicitly documented...

+++ Mike Anderson [Apr 26 16 23:03 ]:

**Comment by nwellnhof** [comment]
Yes, that's how we want it to be working. The accessors for string attributes of nodes like `cmark_node_get_literal` return a buffer that must *not* be freed by the caller. This should be clear from the fact that they return a `const char *`. So @mikeando is right: The render functions are different in this regard.

The rule for cmark is simply: `const char *`s are managed by cmark, `char *`s must be freed by the caller.

**Comment by jgm** [comment]
Reopening since the documentatino can still be improved.
