### ISSUE TITLE
Makefile dependencies too broad

### ISSUE THREAD

**Issue by ericpruitt** [jgm/cmark#129]
I am compiling the cmark CLI tool as a static binary by using `make LDFLAGS=-static build/src/cmark`. On my system, this reports a failure:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/crtbeginT.o: relocation R_X86_64_32 against `__TMC_END__' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.9/crtbeginT.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/libcmark.dir/build.make:535: recipe for target 'src/libcmark.so.0.25.2' failed
make[3]: *** [src/libcmark.so.0.25.2] Error 1
make[3]: Leaving directory '.../cmark/build'
CMakeFiles/Makefile2:114: recipe for target 'src/CMakeFiles/libcmark.dir/all' failed
```

Despite this error, the binary I wanted was built and works fine:

```
cmark$ ldd build/src/cmark
        not a dynamic executable
(1)
cmark$ ls -l build/src/cmark
-rwx------ 1 ericpruitt ericpruitt 1.1M May 28 15:13 build/src/cmark
cmark$ ./build/src/cmark
## HELLO
<h2>HELLO</h2>
cmark$
```

It seems like the Makefile dependencies are broader than necessary.

**Comment by jgm** [comment]
The build is really handled by cmake, and the main Makefile
is just a convenience wrapper around that.

If you comment out the line

    add_library(${LIBRARY} SHARED ${LIBRARY_SOURCES})

in src/CMakeLists.txt, it won't try to build the shared
library.

+++ Eric Pruitt [May 28 16 15:21 ]:

**Comment by ericpruitt** [comment]
Thanks, that works.
