### ISSUE TITLE
Any reason `escape_html` (or `html.h`) doesn't exist in a header file?

### ISSUE THREAD

**Issue by gjtorikian** [jgm/cmark#136]
For [the Commonmarker Ruby wrapper](https://github.com/gjtorikian/commonmarker ), I've been using `houdini_escape_html0` directly to implement escaping HTML. I forgot why, so today when I changed it to `escape_html`, I got the following error:

```
dyld: lazy symbol binding failed: Symbol not found: _escape_html
  Referenced from: /Users/gjtorikian/Development/commonmarker/lib/commonmarker/commonmarker.bundle
  Expected in: flat namespace
```

`html.h` doesn't exist, but `houdini.h` does. Is there any specific reason for this? In the end my code does end up just calling houdini directly as `escape_html` does but I'd like to rely on the official libcmark pattern.

If there isn't a specific reason, I'll open a PR.

**Comment by jgm** [comment]
Neither of these is part of the public API.  The declaration
for the main function defined in html.c lives in cmark.h,
which is the only public header file.

+++ Garen Torikian [Jun 07 16 14:33 ]:

**Comment by gjtorikian** [comment]
Ah, ok.
