### ISSUE TITLE
`cmark_chunk_set_c_str()` can't handle overlapping strings

### ISSUE THREAD

**Issue by foonathan** [jgm/cmark#139]
The part of `cmark_chunk_set_c_str()` [here](https://github.com/jgm/cmark/blob/master/src/chunk.h#L88-L91) allocates new memory directly by overwriting `data`, *then* copying the new string.
If the new string is a part of the old string, this fails.

I was bitten by this because I tried to remove a prefix from the text in a node:

```
cmark_node_set_literal(node, cmark_node_get_literal(node) + x);
```

I don't know if that behavior was intended, if it was, it should be documented.

**Comment by jgm** [comment]
@nwellnhof @vmg any thoughts on this?

**Comment by nwellnhof** [comment]
This is a bug. Good catch!
