### ISSUE TITLE
CRLF support

### ISSUE THREAD

**Issue by btrask** [jgm/cmark#14]
Thanks for your quick work on issue #11. I've continued integrating Cmark with my project.

I've found that when parsing files that use CRLF line endings with Cmark, block quotes extend into subsequent paragraphs, text after lists stays indented, and there are problems with fenced code.

I think the biggest problem is that the test cases don't seem to exercise alternate line endings at all. I'd suggest that _all_ of the test cases should be automatically converted to each type of line ending (LF, CR, and CRLF) during `make test` and Cmark should be expected to pass all of them.

Perhaps there should also be some test cases for a single file brokenly mixing different line endings. This should be possible to handle reasonably intelligently.

I got CRLF support mostly working with some quick patches to blocks.c, which I can post if it would help. I didn't try digging into the tests.

**Comment by btrask** [comment]
I forgot to mention that commonmark.js seems to handle CRLFs correctly in every case I tested.

**Comment by jgm** [comment]
Yes, please do post your patches to blocks.c.  And, good idea about the
testing.

+++ Ben Trask [Mar 15 15 16:53 ]:

**Comment by btrask** [comment]
Sorry for the delay, working on a more complete patch. Needs some changes to scanner.re too, not sure what else yet.
