### ISSUE TITLE
Position tracking of headings is inconsistent

### ISSUE THREAD

**Issue by neongreen** [jgm/cmark#141]
The following demonstration uses Haskell bindings for cmark (unfortunately, I don't know C so I'm unable to port the example to C; I assume the bindings are faithful and don't mess anything up).

Position info for a `#`-style header doesn't include the `#` (i.e. it starts from column 3 instead of column 1):

``` haskell
> let Node _ DOCUMENT [n] = commonmarkToNode [] (T.pack "# hello") in n

Node (Just (PosInfo {startLine = 1, 
                     startColumn = 3, 
                     endLine = 1, 
                     endColumn = 7})) 
     (HEADING 1) 
     [Node Nothing (TEXT "hello") []]
```

Position info for a `=====`-style header *does* include the `=====` (i.e. it ends at line 2, not line 1):

``` haskell
> let Node _ DOCUMENT [n] = commonmarkToNode [] (T.pack "hello\n=====") in n

Node (Just (PosInfo {startLine = 1, 
                     startColumn = 1,
                     endLine = 2,
                     endColumn = 5})) 
     (HEADING 1)
     [Node Nothing (TEXT "hello") []]
```

The latter behavior seems more correct to me and it'd be good if source positions for `#`-style headers behaved the same way.

**Comment by jgm** [comment]
+++ Artyom [Jul 07 16 14:38 ]:
>   The following demonstration uses Haskell bindings for cmark
>   (unfortunately, I don't know C so I'm unable to port the example to C;

You can do

    cmark -t xml --sourcepos

to see what source positions the C library is assigning.

**Comment by neongreen** [comment]
Thanks!

I built cmark (from Github) and fed it the following file:

~~~
# foo

bar
===
~~~

It produced the following output (which exhibits the same behavior as my original Haskell demonstration):

~~~ xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document sourcepos="1:1-4:3" xmlns="http://commonmark.org/xml/1.0">
  <heading sourcepos="1:3-1:5" level="1">
    <text>foo</text>
  </heading>
  <heading sourcepos="3:1-4:3" level="1">
    <text>bar</text>
  </heading>
</document>
~~~
