### ISSUE TITLE
tab/space inconsistency in list items

### ISSUE THREAD

**Issue by jkr** [jgm/cmark#144]
Tab indentation (for code blocks) in list items doesn't work as expected, leading to results which seem to break rule 5.2.1. Below find the expected result with space indentation and the unexpected result when replacing them with tabs.

## Expected result, using spaces

Consider examples [213 and 214](http://spec.commonmark.org/0.25/#example-213), but with only one space after the marker instead of two:

~~~{.markdown}
A paragraph
with two lines.

    indented code

> A block quote.
~~~

produces

~~~{.html}
<p>A paragraph
with two lines.</p>
<pre><code>indented code
</code></pre>
<blockquote>
<p>A block quote.</p>
</blockquote>
~~~

and the following (note: only one space after marker instead of two) 

~~~{.markdown}
1. A paragraph
   with two lines.
   
       indented code
   
   > A block quote.
~~~

produces 

~~~{.html}
<ol>
<li>
<p>A paragraph
with two lines.</p>
<pre><code>indented code
</code></pre>
<blockquote>
<p>A block quote.</p>
</blockquote>
</li>
</ol>
~~~

as was expected.

## Unexpected result, using tabs

Same markdown as above, but with the indented code block indented by a tab. Github's renderer will replace the tab with spaces, but the string is the following:

 `A paragraph\nwith two lines\n\n\tindented code\n\n> A block quote`

~~~
A paragraph
with two lines

	indented code

> A block quote
~~~

We get the same html

~~~{.html}
<p>A paragraph
with two lines.</p>
<pre><code>indented code
</code></pre>
<blockquote>
<p>A block quote.</p>
</blockquote>
~~~

**But** adding the numeric marker with one space, as in the previous example, gives a different result.

`1.␣A paragraph\n␣␣␣with two lines\n\n␣␣␣\tindented code\n\n␣␣␣> A block quote`

~~~{.markdown}
1. A paragraph
   with two lines

   	indented code

   > A block quote
~~~

produces

~~~{.html}
<ol>
<li>
<p>A paragraph
with two lines</p>
<p>indented code</p>
<blockquote>
<p>A block quote</p>
</blockquote>
</li>
</ol>
~~~

The relevant babelmark is [here][babelmark]

[babelmark]: http://johnmacfarlane.net/babelmark2/?text=1.+A+paragraph%0A+++with+two+lines%0A%0A+++%09indented+code%0A%0A+++%3E+A+block+quote%0A

According to rule 5.2.1, since the initial blocks had the same output, I would expect the list item output to be the same as well.

**Comment by jkr** [comment]
BTW, I posted this here because it seems more implementation than spec. But if it (a) is a real issue and (b) should be in CommonMark, let me know and I'll close and move it.

**Comment by jgm** [comment]
Here's an explanation for the behavior.  cmark tries to
behave as much as possible like other Markdown
implementations, which do a preliminary tab->space
conversion before parsing, but without actually
destructively removing the tabs.

Thus,

SPACE + SPACE + TAB

is equivalent to

SPACE + SPACE + SPACE + SPACE

So your text `indented code` looks like it's indented four
spaces, not the six spaces it would need to be.

The implementation is functioning as intended.  But
there is perhaps an issue in the spec, which never really
cleanly absorbed the changes to tab handling.  I do see
why you think that your example should work; after all,
the list item spec says that if you have something with
an indented code block, and you add a list item and indent,
then it should give you a list item with an indented code
block.

However, see also the beginning of section 2.2:
"However, in contexts where indentation is significant for
the document’s structure, tabs behave as if they were
replaced by spaces with a tab stop of 4 characters."

I am not sure what the best way to clarify the spec might
be, but I think it's probably a spec issue.

**Comment by jkr** [comment]
Right -- I guess the question is *when* they start acting like a tabstop: at the left margin or after block-continuation characters are consumed. I came against it because I've been on-and-off playing with a pure haskell version (just to mess around with attoparsec) and the parsing is easier if, after consuming indentation characters, what remains is treated as a new left margin. Not that ease of parsing is a reason for anything.

I'll close and if anything occurs to me to make the spec clearer, I'll submit it there.

**Comment by jkr** [comment]
(Or I suppose I could make it even easier and just run the whole thing through a tab filter before doing anything else.)

**Comment by jgm** [comment]
+++ Jesse Rosenthal [Jul 15 16 10:49 ]:
>   Right -- I guess the question is when they start acting like a tabstop:
>   at the left margin or after block-continuation characters are consumed.

Left margin.  Though I see why that wasn't crystal clear.

>   I came against it because I've been on-and-off playing with a pure
>   haskell version (just to mess around with attoparsec) and the parsing
>   is easier if, after consuming indentation characters, what remains is
>   treated as a new left margin. Not that ease of parsing is a reason for
>   anything.

Good to hear about the project!
