### ISSUE TITLE
Horizontal rule in unordered list causes list to be broken into two

### ISSUE THREAD

**Issue by lambda** [jgm/cmark#148]
The following example, according to [CommonMark 0.26] and [many implementations on Babelmark][Babelmark], should render as an unordered list with two elements, the second of which contains a horizontal rule:

```markdown
-   foo
-   

    * * * * *
```

However, according to [Babelmark], commonmark 0.26.0 renders this as two separate lists, the first one containing an empty second element, and the second containing the horizontal rule.

[CommonMark 0.26]: http://spec.commonmark.org/0.26/
[Babelmark]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+++foo%0A-+++%0A%0A++++*+*+*+*+*

**Comment by jgm** [comment]
It's two separate lists because the list marker changed.

See http://spec.commonmark.org/0.26/#of-the-same-type

So, not a bug.

+++ Brian Campbell [Jul 27 16 06:44 ]:
>   The following example, according to [1]CommonMark 0.26 and [2]many
>   implementations on Babelmark, should render as an unordered list with
>   two elements, the second of which contains a horizontal rule:
>
>-   foo
>-
>
>    * * * * *
>
>   However, according to [3]Babelmark, commonmark 0.26.0 renders this as
>   two separate lists, the first one containing an empty second element,
>   and the second containing the horizontal rule.
>
