### ISSUE TITLE
Building cmark for iOS

### ISSUE THREAD

**Issue by RuiAAPeres** [jgm/cmark#15]
I followed the steps to create a `libcmark.0.18.1.dylib`, but when added to the project I get a:

 > building for iOS Simulator, but linking against dylib built for MacOSX file

How can I make the dylib to iOS?

**Comment by jgm** [comment]
This might require some cmake tweaks.

Did you tell cmake you wanted to build an XCode project?

There's an ios toolchain here which you could try:
https://code.google.com/p/ios-cmake/wiki/HowTo

**Comment by RuiAAPeres** [comment]
@jgm would it be possible to simply import the c files + headers and work with that?

**Comment by jgm** [comment]
Sure.  Note, though, that you'll need a few generated headers
which you can find in build/src after a regular build.

+++ Rui Peres [Mar 17 15 12:31 ]:

**Comment by RuiAAPeres** [comment]
@jgm one quick question (I wasn't able to find an example), how would you go about to generate the AST from the markdown using your lib?

**Comment by jgm** [comment]
parse_document is the function that does that.  See the man page cmark.3.

+++ Rui Peres [Mar 18 15 03:31 ]:
