### ISSUE TITLE
Add basic Vala Bindings

### ISSUE THREAD

**Issue by mdickie** [jgm/cmark#150]
I would be quite nice if there were basic bindings available. Here is an basic cmark.vapi file:

```
[CCode (cheader_filename = "cmark.h")]

namespace Cmark {

[CCode (cname = "cmark_markdown_to_html")]
string markdown_to_html(string str, size_t len, int options);

}
```

Of course this file should be installed correctly into /usr/share/vala/vapi. However, I have no idea how to do this in CMake, otherwise i would have done a pull request.

**Comment by kainjow** [comment]
IMO, probably would be best maintained as a separate library.

**Comment by fabrixxm** [comment]
If anyone is still interested, I've just wrote a vapi file for libcmark

https://github.com/fabrixxm/libcmark-vapi
