### ISSUE TITLE
Documentation issue - empty string vs NULL

### ISSUE THREAD

**Issue by foonathan** [jgm/cmark#155]
Because this is the second time I ran into it, I decided to report it.

According to the documentation the string-returning functions (like, for example `cmark_node_get_url()`) return "an empty string" if there is no string to return.
In C, an empty string is a `const char*` to `""` (a string literal with no text).
This returns a valid pointer that you can dereference leading to the character '\0' (i.e. ASCII null).
But the functions actually return `NULL` which is a pointer you cannot dereference.

I suggest that you either change the documentation or the functions. I'd advocate for changing the implementation because it would allow usages like checking for the first character of the string (`*str == x`) without an additional check if the pointer is valid.

**Comment by jgm** [comment]
Can you give a simple minimal example to reproduce this?
Also, let us know what version you're using.

It should return an empty string (string literal with no
text), not a NULL.  And, it did do this when I tested it
just now (creating a link node and then immediately getting
the url).

However, if the node is not a CMARK_NODE_LINK or
CMARK_NODE_IMAGE, then the function will return a NULL.
Are you calling it, perhaps, on a function that is not
a link or image?

+++ Jonathan Müller [Sep 25 16 11:01 ]:

**Comment by foonathan** [comment]
> Are you calling it, perhaps, on a function that is not a link or image?

I haven't debugged it further, I just skimmed the source code.
Yes, that could be the case indeed, my apologies.

Then the issue is simply a request to document that behavior or return an empty string in that case as well.
