### ISSUE TITLE
cmark installing cmake files

### ISSUE THREAD

**Issue by juhp** [jgm/cmark#186]
Well it is not that big a deal but at least cmark-0.27.1 now seems to install
`$libdir/cmake/cmark.cmake` and `$libdir/cmake/cmark-release.cmake`.

I don't know if it is intentional?  Looking at the files suggests they may not be user facing?

(cmark-0.25.2.1 doesn't install them.)

**Comment by foonathan** [comment]
Those files are used by CMake's find_package() facility, so they should be installed.

**Comment by juhp** [comment]
Okay thanks!
