### ISSUE TITLE
`cmark_parse_inlines` dead code?

### ISSUE THREAD

**Issue by kivikakk** [jgm/cmark#189]
I've looked at [this set of lines](https://github.com/jgm/cmark/blob/b75890e0fd7abb995d083b795c2cd45703b7cb22/src/inlines.c#L1167-L1169) a number of times, and it's only now while doing a small translation of `cmark` that I've really come to realise it's almost certainly dead.  The part in question, introduced in https://github.com/jgm/cmark/commit/2efea7a064e911311979e0387d6d99abe9c6020a:

```c
process_emphasis(&subj, NULL);
// free bracket and delim stack
while (subj.last_delim) {
  pop_bracket(&subj);
}
while (subj.last_bracket) {
  pop_bracket(&subj);
}
```

Specifically, the `while (subj.last_delim)` part is (by induction) dead — if it wasn't dead and actually did execute, there'd be an infinite loop, as `pop_bracket` doesn't touch `last_delim` (and didn't as of that commit).

Am I right in thinking this should be excised entirely?

**Comment by jgm** [comment]
Good catch.  This was added in 2efea7a064e911311979e0387d6d99abe9c6020a
but there's no explanation why.  Clearly it doesn't do what it is advertised as doing.

**Comment by jgm** [comment]
Let me know what you think of the fix.

**Comment by kivikakk** [comment]
The fix looks good. As I continue delving into the inline parser I'll see if I can make any proof about whether the delimiter stack will be empty (or show that it could be non-empty).
