### ISSUE TITLE
Roundtripping issues with escaped entities

### ISSUE THREAD

**Issue by kivikakk** [jgm/cmark#190]
Currently we cannot roundtrip escaped entities through CommonMark:

``` shell
root@0063e4e160bd:/src/cmark# echo '\&trade;'
\&trade;
root@0063e4e160bd:/src/cmark# echo '\&trade;' | build/src/cmark-gfm -t commonmark
&trade;
root@0063e4e160bd:/src/cmark# echo '&trade;' | build/src/cmark-gfm -t commonmark
™
```

The issue lies in the implementation of [`render.c`'s `S_out`](https://github.com/jgm/cmark/blob/12501f1000f592ff67cca98b6733f0bfa3115f9f/src/render.c#L65): it calculates `nextc`, which is eventually passed to `commonmark.c`'s `outc`, which itself escapes `&` iff `cmark_isalpha(nextc)`.

The problem is that `S_out` is given at most one node's content at a time in `source` (and of course, often less). Without normalising text nodes, a literal (escaped) `&` is guaranteed to be in a node separate to any adjacent text nodes (as created by `handle_backslash`), and therefore this case will never trigger.

Normalizing text nodes, then, predictably fixes the problem:

``` shell
root@0063e4e160bd:/src/cmark# echo '\&trade;' | build/src/cmark-gfm -t commonmark --normalize
\&trade;
```

**Comment by jgm** [comment]
We should probably just build in normalization (i.e. not
make it an option).  Last time I checked, the performance
implications were pretty minimal.
