### ISSUE TITLE
Support for subscript and superscript

### ISSUE THREAD

**Issue by rogersachan** [jgm/cmark#191]
For those of us who don't want to use HTML tags to do this, will this ever be implemented? [Beegit's Cheat sheet](https://beegit.com/markdown-cheat-sheet) says `32^nd^` should give superscript and `H~2~O` should give subscript, but that is not working in my text editor.

**Comment by jgm** [comment]
Possibly this extension will be added later, but this implementation conforms to the spec;
discussion should take place at talk.commonmark.org.
