### ISSUE TITLE
Escaped spaces in link destination

### ISSUE THREAD

**Issue by ScottAbbey** [jgm/cmark#192]
The combination of the following two statements from section 6.5, Links, in the CommonMark spec:

> The destination cannot contain spaces or line breaks, even if enclosed in pointy brackets:

> Note that a backslash before a non-escapable character is just a backslash:

Leads me to believe that the following:

Input:
```
[a](te\ st)
```

Output:
```
<p><a href="te%5C%09st">a</a></p>
```

Behavior in this implementation of CommonMark is incorrect.

The javascript reference implementation sees this as `<p>[a](te\ st)</p>` instead, which seems to agree with the spec.

**Comment by jgm** [comment]
Right. This looks like a bug.
