### ISSUE TITLE
Replace bullets with images for lists?

### ISSUE THREAD

**Issue by ashleybeck1** [jgm/cmark#199]
I'm just wondering if it is possible to replace bullets in lists with images provided by the projects bundle?

example: 
```
ul {
    list-style-image: url('sqpurple.gif')
}
```

**Comment by jgm** [comment]
I'm not sure what you're asking.  Of course you can use
whatever CSS you like with the HTML produced by this
library.

+++ Ashley [May 19 17 13:02 ]:
