### ISSUE TITLE
Delimiter type of bulleted list

### ISSUE THREAD

**Issue by PavloKapyshin** [jgm/cmark#201]
While testing `cmark_node_get_list_delim` I noticed that it returns `CMARK_PERIOD_DELIM` for bulleted list. This was a bit unexpected (`CMARK_NO_DELIM` seems natural). Should it be this way?

JavaScript implementation gives `null`  in such case:

```js
> reader.parse("* one\n* two\n\n").firstChild.listType
< "bullet"
> reader.parse("* one\n* two\n\n").firstChild.listDelimiter
< null
```

**Comment by nwellnhof** [comment]
Looks like a bug. [This line](https://github.com/jgm/cmark/blob/6313fff5f9482bdc0489dd19bf9c4ff6ed817e71/src/blocks.c#L418) should probably be removed, or changed to initialize with `CMARK_NO_DELIM`.

**Comment by jgm** [comment]
Agreed. I suspect this goes back to a time when we didn't have
CMARK_NO_DELIM.  We should initialize with CMARK_NO_DELIM.

+++ Nick Wellnhofer [May 29 17 18:14 ]:
