### ISSUE TITLE
List start of bulleted list

### ISSUE THREAD

**Issue by PavloKapyshin** [jgm/cmark#202]
`cmark_node_get_list_start` documentation says it returns starting numbers for lists that are ordered. In reality it also returns `1` for bulleted lists (`0` is expected).

In following examples `node` is an unordered list got from `"* one\n* two\n\n"`.

cmark:

```pycon
>>> node_get_list_type(node) == BULLET_LIST
True
>>> node_get_list_start(node)
1
```

commonmark.js:

```js
> node.listType
< "bullet"
> node.listStart
< null
```

**Comment by jgm** [comment]
Why would you expect to get 0 rather than any other number?  The documented behavior is that it returns start numbers for ordered lists.  Behavior is undefined when you call it on other kinds of nodes.

**Comment by PavloKapyshin** [comment]
Because documentation says that it returns “starting number of node, if it is an ordered list, otherwise 0”. It is not an ordered list, so “otherwise”. Or am I not getting something?

**Comment by jgm** [comment]
Ah, I stand corrected.  I didn't know this was documented
behavior.  I'll fix it, thanks.

+++ Pavlo Kapyshin [Jun 02 17 06:51 ]:
