### ISSUE TITLE
Latex output

### ISSUE THREAD

**Issue by xelatihy** [jgm/cmark#31]
Two questions about possible Latex output.

1. Is this a planned feature?
2. If one were to implement it, is there a chance it would be merge?

Thanks.

**Comment by jgm** [comment]
+++ xelatihy [May 01 15 20:55 ]:
>   Two questions about possible Latex output.
>    1. Is this a planned feature?

I think it would make sense.

>    2. If one were to implement it, is there a chance it would be merge?

Yes, I'd certainly consider a PR.
