### ISSUE TITLE
Memory leak in `cmark_consolidate_text_nodes`

### ISSUE THREAD

**Issue by elibarzilay** [jgm/cmark#32]
AFAICT, the call it does a call to `cmark_node_set_literal` copies the string from `buf`, but that string is never copied.  It's easy to verify the leak with running it in a loop and looking at the memory (which is how I caught it) then adding a `free` for the detached string and the leak is gone.

[I'd submit it as a PR, but it seems silly to put stuff in an allocated string, then copying it and freeing the first.  A more proper solution would be some way to signal a request to not copy the text (which `cmark_node_set_literal` could get as a new argument which will be passed on to `cmark_chunk_set_cstr`) but that's an API change, so I'm just reporting it...]

**Comment by jgm** [comment]
This can also be revealed by

    valgrind --leak-check=full --dysmutil=yes \
      build/src/cmark --normalize README.md

I have improved 'make leakcheck' to detect this case.

Could you say more about your "more proper solution"?  I
didn't quite understand.  I just pushed a fix that avoids
allocating the extra string, but you may have an even better
idea.

**Comment by elibarzilay** [comment]
Well, what I tried was adding a `nocopy` argument to `cmark_node_set_literal`, and that leads to a new argument to `cmark_chunk_set_cstr`.  It's not great, especially since it adds an argument to a public function -- but maybe it makes sense to have it there.  (And since I don't know the answer I left it as a comment only.)

I'm not sure about it, but it looks like after your fix it still double-copies the string (allocates the string buffer, then allocates a copy, then frees the first copy).
