### ISSUE TITLE
compile fail, missing dependency

### ISSUE THREAD

**Issue by fommil** [jgm/cmark#40]
are you maybe forgetting to declare a dependency?
```
 cabal install cmark
Resolving dependencies...
Configuring cmark-0.3.2...
Building cmark-0.3.2...
Failed to install cmark-0.3.2
Build log ( /home/fommil/.cabal/logs/cmark-0.3.2.log ):
Configuring cmark-0.3.2...
Building cmark-0.3.2...
Preprocessing library cmark-0.3.2...
[1 of 1] Compiling CMark            ( dist/build/CMark.hs, dist/build/CMark.o )

CMark.hsc:61:11: Not in scope: `TF.withCStringLen'

CMark.hsc:72:5:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)

CMark.hsc:79:3: Not in scope: `TF.withCStringLen'

CMark.hsc:85:12:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)

CMark.hsc:324:22:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)
cabal: Error: some packages failed to install:
cmark-0.3.2 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by vyp** [comment]
Builds fine for me. (via `cabal install cmark`) ... Anything I might have missed?

**Comment by fommil** [comment]
On Debian Jessie...

```
~ rm -rf ~/.cabal ~/.ghc
~ cabal update
Config file path source is default config file.
Config file /home/fommil/.cabal/config not found.
Writing default configuration to /home/fommil/.cabal/config
Downloading the latest package list from hackage.haskell.org
~ cabal install cmark
Resolving dependencies...
Downloading cmark-0.3.2...
Configuring cmark-0.3.2...
Building cmark-0.3.2...
Failed to install cmark-0.3.2
Build log ( /home/fommil/.cabal/logs/cmark-0.3.2.log ):
[1 of 1] Compiling Main             ( /tmp/cmark-0.3.2-24169/cmark-0.3.2/dist/setup/setup.hs, /tmp/cmark-0.3.2-24169/cmark-0.3.2/dist/setup/Main.o )
Linking /tmp/cmark-0.3.2-24169/cmark-0.3.2/dist/setup/setup ...
Configuring cmark-0.3.2...
Building cmark-0.3.2...
Preprocessing library cmark-0.3.2...
[1 of 1] Compiling CMark            ( dist/build/CMark.hs, dist/build/CMark.o )

CMark.hsc:61:11: Not in scope: `TF.withCStringLen'

CMark.hsc:72:5:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)

CMark.hsc:79:3: Not in scope: `TF.withCStringLen'

CMark.hsc:85:12:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)

CMark.hsc:324:22:
    Not in scope: `TF.peekCStringLen'
    Perhaps you meant `B.packCStringLen' (imported from Data.ByteString)
cabal: Error: some packages failed to install:
cmark-0.3.2 failed during the building phase. The exception was:
ExitFailure 1
~ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library 
~ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
```

**Comment by fommil** [comment]
@vyp maybe you have the missing dep installed already?

**Comment by fommil** [comment]
@tarleb suggested doing this

```
cabal install text-1.2.1.0 --force-reinstalls
```

which fixes the problem and then `cmark` can install.

**Comment by vyp** [comment]
> @vyp maybe you have the missing dep installed already?

Ah yes most likely. I thought I test in a fresh environment but turns out I had already installed pandoc here.

**Comment by tarleb** [comment]
@fommil: If you are on Jessie, you might have Haskell packages installed via APT.  I found that purging all libghc-\* helps when building new packages.  Alternatively, try pinning haskell packages to sid.

##### `/etc/apt/sources.list`:

```
# Jessie
deb     http://ftp.de.debian.org/debian/ jessie         main non-free contrib
deb-src http://ftp.de.debian.org/debian/ jessie         main non-free contrib

deb     http://security.debian.org/      jessie/updates main contrib non-free
deb-src http://security.debian.org/      jessie/updates main contrib non-free

# Sid
deb     http://ftp.de.debian.org/debian/ sid            main non-free contrib
deb-src http://ftp.de.debian.org/debian/ sid            main non-free contrib
```

##### `/etc/apt/preferences`

```
Package: *
Pin: release n=sid
Pin-Priority: 600

Package: *
Pin: release n=jessie
Pin-Priority: 800

Package: libghc-*
Pin: release n=sid
Pin-Priority: 900
```

**NOTE**: I havn't tried it.

**Comment by vyp** [comment]
@fommil @tarleb I'm not going to pretend I'm an expert at this, but I might hold back from tying haskell packages to sid for now, especially since you already said force installing text-1.2.1.0 solves the issue, because I'm not sure how easy it would be rollback to stable/testing once you go sid? I haven't used debian in a while (and even then I only used sid), but I heard it's easy to switch from stable --> testing --> unstable then it is the other way around? If it is easy to go back or you know what you're doing then of course don't worry, I'm just being cautious.

At least until someone comes and clarifies whether or not a dependency declaration is actually missing or not.

**Comment by fommil** [comment]
I think cmark and pandoc are missing the correct dependency declarations and when someone with the requisite cabal foo fixes it, things should work. I might purge all Haskell apps from apt and go fully cabal. It's the same deal with java apps, there is a standard package manager one you go into that realm so apt should focus on integration instead of repackaging.

**Comment by fommil** [comment]
@tarleb you're quite right it was interaction with the jessie system xmonad libraries. I thought cabal isolated all that sort of stuff, I can understand what people mean by "cabal hell" now.

Unfortunately, on an unrelated issue `xmonad-contrib` has a failure... so I'm between a rock and a hard place.

**Comment by jgm** [comment]
Note: this repository, jgm/cmark, is for the C library.
jgm/cmark-hs is the Haskell binding (cmark on Hackage).
