### ISSUE TITLE
PDB of cmark.exe is overwritten by DLL's PDB on Windows

### ISSUE THREAD

**Issue by nwellnhof** [jgm/cmark#46]
If you build a debug version on Windows (`nmake BUILD_TYPE=Debug`), the PDB file for cmark.exe (cmark.pdb) is overwritten by the PDB file of cmark.dll with the same name. This makes debugging a bit painful. For now, I'm resorting to temporarily renaming the DLL in CMakeLists.txt. It would be nice if we could somehow build the executable and library in separate directories.

**Comment by jgm** [comment]
Did you see
http://www.cmake.org/cmake/help/v3.0/prop_tgt/PDB_NAME.html
I think it would be better to set this for Windows, rather than have different directories.

**Comment by nwellnhof** [comment]
Yeah, that makes sense. I didn't know about this option and I'll give it a try.

**Comment by jgm** [comment]
@nwellnhof, did you try this?  If it worked, let's commit it and close this issue.
