### ISSUE TITLE
-pg flag is added to Debug and Profile builds on every platform

### ISSUE THREAD

**Issue by nwellnhof** [jgm/cmark#47]
The `-pg` flag shouldn't be used for Debug builds at all. For Profile builds, it should only be used with compilers that support it (gcc and clang).

**Comment by jgm** [comment]
I think I was just trying to avoid having a separate Profile
target.  But I'd be in favor of adding one and doing it
right.  Would you like to  submit a PR?


+++ Nick Wellnhofer [May 29 15 14:33 ]:

**Comment by nwellnhof** [comment]
Can't we just remove the `-pg` flag? It seems that CMake already provides the necessary flags for Debug and Profile builds.

**Comment by jgm** [comment]
As far as I can see, cmake doesn't automatically add profiling flags for the Profile build type.  (Confirmed by experiment and google.)  But I removed -pg from the Debug build.
