### ISSUE TITLE
FFI bindings

### ISSUE THREAD

**Issue by txdv** [jgm/cmark#60]
Hey guys, I saw that the version strings are external symbols to variables.

Some programming languages support only ffi, as in, all external calls can be made only through functions, variables are not accessible even if they are external, for example C#.

Could we get additional functions to retrieve the version string and integer number?

**Comment by jgm** [comment]
Makes sense to me.  And maybe the variable isn't needed if we have a function.  What do you think, @nwellnhof ?

**Comment by nwellnhof** [comment]
Yes, we should add these functions to support bindings based on FFI. We could also remove the global version variables then. I'd like to keep the version macros, though.

**Comment by jgm** [comment]
>   Yes, we should add these functions to support bindings based on FFI. We
>   could also remove the global version variables then. I'd like to keep
>   the version macros, though.

Agreed, the macros are useful in situations where the function would not be.

**Comment by txdv** [comment]
I will make a pull request then.
