### ISSUE TITLE
Compilation Fails in Xcode

### ISSUE THREAD

**Issue by nuudles** [jgm/cmark#65]
In Xcode, I'm getting a compile error:

`cmark/src/buffer.c:187:10: Implicit declaration of function '_vscprintf' is invalid in C99`

Is line 184 of buffer.c supposed to be:

`#ifdef HAVE_C99_SNPRINTF` instead of `#ifndef HAVE_C99_SNPRINTF`?

**Comment by jgm** [comment]
It is supposed to be `#ifndef`.
So, it looks as if `HAVE_C99_SNPRINTF` is not defined in
your setup, even though with xcode and clang it should be.
(As the code comment says, we assume that if it's not
defined, it means we're on Windows.)

This macro is defined in src/CMakeLists.txt 141-4:

    CHECK_C_SOURCE_RUNS("
      #include <stdio.h>
      int main() { return snprintf(NULL, 0, \"123\") == 3 ? 0 : 1; }
    " HAVE_C99_SNPRINTF)

It should be defined automatically by cmake if your C
compiler can successfully compile this little program, and
it returns a 0 exit code when run.

Btw, I just tested on xcode, and had no problems.
Here's what I did:

    mkdir xcode
    cd xcode
    cmake -G Xcode ..
    open cmark.xcodeproj/

Press the compile button.  The build succeeded.  Did you use
a different procedure, perhaps not using cmake?

If you don't want to use cmake, you might have success just
setting the `HAVE_C99_SNPRINTF` macro manually.  (There might
be a few others you also need to set, though.)

+++ Christopher Luu [Jul 13 15 20:27 ]:

**Comment by nuudles** [comment]
Ahh, I see. I'm using the [CocoaMarkdown](https://github.com/indragiek/CocoaMarkdown) wrapper, which doesn't appear to use cmake. I'll play around with it some and get it working. Thanks for the quick response!
