### ISSUE TITLE
CRLF regression

### ISSUE THREAD

**Issue by btrask** [jgm/cmark#68]
I just updated the version of cmark I am using and found that CRLF support was broken in bd3b24523fe30934c287698c53b4f2623557fa58. CR and LF endings independently work fine, but the logic that treated CRLF as one line break was over-simplified. Now CRLF gets handled as two line breaks, one CR and one LF.

The main example of this can be seen at https://github.com/jgm/cmark/commit/bd3b24523fe30934c287698c53b4f2623557fa58#diff-f4eff1b97e63a76ec31f3bdea11f10deL568 blocks.c line 568 where the logic that would eat up to two characters (one CR and one LF) was replaced by a single check that would only eat one character (either CR or LF but not both).

I think this is an argument for running the full test suite with all three line ending modes.

Thanks.

Edit: forgot to provide a test case.

```markdown
line
line
```

Converted with `cmark --hardbreaks crlf.md`. Output is:

```
<p>line<br />
<br />
line</p>
```

I don't believe this problem is specific to the hardbreaks option, that's just where I happened to notice it first.

**Comment by jgm** [comment]
I think it is specific to the hardbreaks option (so it wouldn't have been caught even if we'd run the spec tests with different line break options).  I've added an api test that catches this.
I'll look into a fix.
