### ISSUE TITLE
Get rid of cmake dependency?

### ISSUE THREAD

**Issue by chriseidhof** [jgm/cmark#69]
I think it'd be really nice to get rid of the cmake dependency (from a user's perspective, at least). Are there big implications from the maintainer's perspective? I'm willing to help out and do the work (but of course, only if we agree this is a good idea).

**Comment by kainjow** [comment]
IMO, CMake is a huge life saver for projects. Going back to Makefiles for each platform and Visual Studio projects would be a nightmare.

**Comment by jgm** [comment]
+++ Chris Eidhof [Aug 06 15 00:45 ]:
>   I think it'd be really nice to get rid of the cmake dependency (from a
>   user's perspective, at least). Are there big implications from the
>   maintainer's perspective? I'm willing to help out and do the work (but
>   of course, only if we agree this is a good idea).

What's the alternative?  We need the project to build on a
multitude of platforms, including Windows.  cmake makes that
possible.

**Comment by chriseidhof** [comment]
Ok, I see. I figured a plain Makefile would be the alternative... But I'm blissfully unaware of the advantages of cmake (have close to zero experience in maintaining a C library).

My (very specific) use-case is that I wrapped this up as a [CocoaPod](https://cocoapods.org). There it'd help a lot if people don't need to install cmake. Anyway, let's close this ticket?

**Comment by jgm** [comment]
I don't know anything about CocoaPod.  As I said, if you're
targeting this one platform, you can probably just build
your own simple Makefile and extract the source files you
need.  (Note that some of the headers are built by cmake,
so you'll have to extract them from the build directory.)
That's what I do in my Haskell bindings.

+++ Chris Eidhof [Aug 07 15 01:41 ]:

**Comment by arielelkin** [comment]
See https://github.com/jgm/cmark/issues/91

**Comment by MathieuDuponchelle** [comment]
https://github.com/mesonbuild/meson should be mentioned here :)

**Comment by kainjow** [comment]
So with Meson, you now also need Python and Ninja. How is that better than CMake which has no dependencies?

**Comment by MathieuDuponchelle** [comment]
Not saying it's better, just saying it ought to be mentioned.

**Comment by nwellnhof** [comment]
I just want to use the opportunity and point interested readers to [Charmonizer](https://github.com/apache/lucy-charmonizer). Its a build system that configures C projects using only C89. We use it at Apache Lucy, but it's not really ready for public consumption, mostly due to lack of documentation.

To my knowledge, it's the only effort to provide a cross-platform build system for C with no external dependencies except for a POSIX-compatible make or nmake.
