### ISSUE TITLE
Discern `html` and `xhtml` output

### ISSUE THREAD

**Issue by tin-pot** [jgm/cmark#80]
The `html` output option currently produces XML-style empty elements (like `<br />`) - these are not valid in HTML, but required in XHTML. Implementing a separate `xhtml` output option is trivial: duplicate and modify the `html.c` source file into `xhtml.c` (see tin-pot/cmark@06ee9493da70e9549e55f4ac617a06095bac1f07).

**Comment by jgm** [comment]
I'm not really sure it's worth it.  `<br />` and `<hr />` are valid in HTML 5.  See the first answer [here](http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5) -- they are treated as identical to `<br>` and `<hr>`.  The reason I chose to use these forms is that the output can then be used in EPUBs, which require valid XML.

**Comment by tin-pot** [comment]
Duplicating the whole HTML renderer is indeed rather clumsy and probably too much bloat, true. I didn't think of HTML5 - which is no longer a SGML application. Generating XML is probably sufficient today, and I'm happy with twisting my clone for other needs.
