### ISSUE TITLE
Error when installing cmark with Cocoapods

### ISSUE THREAD

**Issue by arielelkin** [jgm/cmark#91]
Here's my podfile:

```
platform :ios, '8.0'
pod 'cmark', '0.21.0'
```

Here's the output of `pod install`:

```
Analyzing dependencies
Downloading dependencies
Installing cmark (0.21.0)
[!] /bin/bash -c 
set -e
echo `pwd`
sed -i '' 's/include <\(cmark.*\)>/include "\1"/' src/cmark.h
mkdir -p build; cd build && cmake -G Xcode ..

/Users/Me/Library/Caches/CocoaPods/Pods/Release/cmark/0.21.0-0868a
/bin/bash: line 4: cmake: command not found
```

Using Cocoapods v0.39.0

But isn't [the cmark podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/cmark/0.21.0/cmark.podspec.json#L27) bypassing `cmake` ?

**Comment by chriseidhof** [comment]
No, we're not bypassing cmake in the pod spec.

**Comment by arielelkin** [comment]
So I can't use this pod if I don't have cmake installed?

**Comment by jgm** [comment]
This seems to be more of a cocoapods issue than a cmark one.  cmark's build system requires cmake (just like many other C libraries and programs).  There are good reasons for that requirement, as it allows the build to work on a large number of different platforms, including Windows.

I don't know anything about cocoapods, but in principle you could run cmake before packaging, and package up the cmake build directory to remove the cmake dependency.  You could probably also create a patch that adds a custom Makefile and perhaps some needed header files.  So if it's advantageous not to require cmake in the cocoapods distribution of cmark, there are ways this could be achieved.

Anyway, closing this here.

**Comment by kainjow** [comment]
BTW, if you need CMake, it's easy to get from [Homebrew](http://brew.sh):

    brew install cmake

**Comment by sadlerjw** [comment]
@arielelkin I had the same problem - seems to be a problem with Cocoapods's environment - it doesn't look for executables in `/usr/local/bin`, which is where Homebrew installs it. If you can create a symbolic link that should solve your problem. (But as @jgm suggests, this is in fact a Cocoapods issue)
