### ISSUE TITLE
Custom blocks should allow any type of children

### ISSUE THREAD

**Issue by nwellnhof** [jgm/cmark#96]
Currently, custom blocks only allow block children. They should allow children of any type (especially inline), so that a custom block can replace any other block, for example a paragraph or a list.

**Comment by jgm** [comment]
Agreed - I'd actually already changed this in the DTD, but
forgot to change it in libcmark.

One question I had is whether it would make sense to allow
CUSTOM_INLINE to contain block children, or whether that's
a bridge too far.  (I had trouble thinking of any real-world
case where this would make sense, although it might make
sense for footnotes.)

+++ Nick Wellnhofer [Dec 30 15 11:44 ]:

**Comment by nwellnhof** [comment]
I think it's OK if CUSTOM_INLINE doesn't allow block children.

Another question is whether CUSTOM_BLOCK should also allow ITEM children.

**Comment by jgm** [comment]
+++ Nick Wellnhofer [Dec 30 15 17:06 ]:
>   I think it's OK if CUSTOM_INLINE doesn't allow block children.
>
>   Another question is whether CUSTOM_BLOCK should also allow ITEM
>   children.

Yes, I wasn't sure about this.  According to the DTD,
they're not allowed.  (Of course, that could change too.)

Here's a case for allowing them.  Suppose you want to write
a filter that uses a custom 'enumerate' environment (with
extra options) for latex lists.  The `\item` parts could
stay the same.
