### ISSUE TITLE
links with quoted '(' and ')' in link-destination get parsed incorrectly

### ISSUE THREAD

**Issue by jberkel** [jgm/cmark#97]
```
# 0.22.0
$ echo "[foo](bar\(baz\))" | build/src/cmark
<p><a href="bar(baz)">foo</a></p>

# 0.23.0
$ echo "[foo](bar\(baz\))" | build/src/cmark
<p>[foo](bar(baz))</p>
```

After a git-bisect it looks like this got introduced with b59da4fc9c35b9def682294de1c521b32cd859e9 / #82.

**Comment by jgm** [comment]
re2c is doing this, I think:

`bar` as regular text
`\` as `[\\]`
match `(baz\))` as an `in_parens_nosp`
then it has already gobbled the concluding `)`

Using `[\\][^()]` would not allow the case where the link
destination ends in `\`, e.g. `[foo](bar\ "title")`.
(And this is the pattern that got us in trouble with #82.)

But I think I can special-case that...

+++ Jan Berkel [Jan 11 16 05:08 ]:
