### ISSUE TITLE
Reverse renderer from HTML to Markdown

### ISSUE THREAD

**Issue by adib** [jgm/cmark#99]
It would be great if CommonMark reference implementation can also do round-trip between HTML and Markdown. That is, converting a simple HTML document to Markdown and extract the important tags relevant to markdown (emphasis, bold, paragraphs, line breaks, etc).

After two conversion trips then the resulting HTML/Markdown should be stable. The first conversion from HTML to Markdown would strip off irrelevant tags but after this initial simplification phase, any subsequent conversions shouldn't alter the document. That is, after the first HTML to Markdown conversion, rendering Markdown to HTML and then back again would result in the same Markdown document as original no matter how many cycles it goes through.

**Comment by jgm** [comment]
I've got a little lua library that goes from html to
commonmark.

https://github.com/jgm/html2cmark

You can also use pandoc:

    pandoc -f html -t commonmark

Both approaches use cmark's commonmark renderer.  They've
also both been tested with round-trips.  (Pandoc passes
these for the spec tests; html2cmark doesn't pass it on the
examples with invalid HTML, but that's not a big deal I
think.) 

I don't think it's appropriate to add this to the reference
implementation, as it requires a full HTML parser; it really
should be a separate tool.

+++ Sasmito Adibowo [Feb 02 16 05:26 ]:
